package Sandbox;

public class Constants {

    public static final String QUERY_SELECT_AP1 = "SELECT EMPLEADOS.APELLIDOS, EMPLEADOS.NOMBRE, EMPLEADOS.ID, EMPLEADOS.SALARIO FROM EMPLEADOS WHERE EMPLEADOS.SALARIO<12000";


}
